# Generated by Django 5.1.2 on 2024-10-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('position', models.JSONField()),
                ('rotation', models.JSONField()),
                ('color', models.CharField(max_length=7)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
